"""
Constants for topic tags, keywords, and patterns.
Migrated from V2 - Core domain knowledge for topic classification.
"""

# Canonical Topic Tags
TOPIC_TAGS = [
    "Treatment selection",
    "Clinical efficacy",
    "Safety profile",
    "AE management",
    "Biomarker testing",
    "Mechanism of action",
    "Diagnostic workup",
    "Treatment indication",
    "Study Design",
    "Patient-centered care",
]

# Topic keyword patterns for detection
# Format: topic -> list of keyword patterns (case-insensitive)
TOPIC_KEYWORDS = {
    "Treatment selection": [
        r"which treatment",
        r"what treatment",
        r"recommended treatment",
        r"recommended therapy",
        r"should receive",
        r"choose",
        r"select",
        r"preferred",
        r"most appropriate",
        r"next treatment",
        r"first-line treatment",
        r"second-line treatment",
    ],
    "Clinical efficacy": [
        r"response rate",
        r"orr",
        r"pfs",
        r"os",
        r"overall survival",
        r"progression-free survival",
        r"efficacy",
        r"outcome",
        r"benefit",
        r"showed",
        r"improved",
        r"derived benefit",
        r"trial results",
        r"trial showed",
        # Trial names
        r"keynote", r"checkmate", r"dreamm", r"flaura", r"ascertain", r"lotis", r"s1826", r"swog",
        r"tropion", r"compass", r"sascia", r"carmen", r"destiny", r"ispy", r"emerald",
        r"empower", r"mylung", r"dart", r"athena", r"monaleesa", r"monarch",
        r"paloma", r"pivot", r"clear", r"impassion", r"imbrave",
        r"phase.*\d+.*trial", r"phase.*\d+.*study",
        # Findings patterns
        r"key.*findings", r"findings.*from", r"best.*describes.*key.*findings",
        r"what.*was.*observed", r"observed.*in.*patients",
        r"pcr.*rate", r"pathologic.*complete.*response", r"pathological.*complete.*response",
        r"which.*best.*describes.*key.*findings",
        r"best.*describes.*findings",
    ],
    "Safety profile": [
        r"safety considerations",
        r"safety profile",
        r"tolerability",
        r"adverse events",
        r"side effects",
        r"most common.*ae",
        r"most common.*adverse",
        r"most common.*adverse event",
        r"most common.*adverse.*event",
        r"key toxicity",
        r"common toxicity",
        r"most common.*toxicity",
        r"most frequent.*ae",
        r"most frequent.*adverse",
        r"key safety concern",
        r"safety concern",
        r"grade.*adverse event",
        r"grade.*or.*greater.*adverse",
        r"grade.*or.*greater.*ae",
        r"treatment-related.*adverse",
        r"treatment-related.*ae",
        r"treatment-related.*adverse event",
        r"black box warning",
        r"warning.*adverse",
        r"incidence.*adverse",
        r"discontinuation.*adverse",
    ],
    "AE management": [
        r"how should.*be managed",
        r"how to manage",
        r"dose reduction",
        r"toxicity",
        r"ae management",
        r"side effect management",
        r"develops.*what",
        r"develops.*how",
        r"patient develops",
        r"recommended course of action",
        r"what to do",
        r"next step",
    ],
    "Biomarker testing": [
        r"biomarker testing",
        r"molecular testing",
        r"genetic testing",
        r"which test",
        r"what testing",
        r"testing.*recommended",
        r"testing.*indicated",
    ],
    "Mechanism of action": [
        r"mechanism of action",
        r"moa",
        r"how does.*work",
        r"what does.*target",
        r"therapeutic target",
        r"drug target",
        r"adc target",
        r"targets",
        r"which.*targets",
        r"molecular target",
        r"inhibition of\s+\w+\s+(?:in|blocks|prevents)",
        r"signaling pathway",
        r"pathway.*believed to",
        r"believed to.*contribute",
        r"anti[- ]?CD\d+\s+(?:monoclonal|antibody)",
        r"monoclonal antibody.*target",
        r"JAK\d?\s+inhibitor",
        r"ROCK\d?\s+inhibitor",
        r"CSF[- ]?\d?R?\s+(?:inhibitor|signaling|pathway)",
        r"blocks?\s+phosphorylation",
        r"(?:inhibits?|blocks?|targets?)\s+(?:the\s+)?(?:\w+\s+)?(?:receptor|kinase|pathway)",
        r"what is the.*target\s+(?:for|of)",
        r"functions?\s+by\s+(?:causing|producing|inhibiting|blocking)",
        r"(?:employed|used)\s+(?:during|for|in)\s+(?:the\s+)?development",
        r"(?:works|acts)\s+by\s+\w+ing",
        r"receptor\s+shedding",
        r"produce\s+(?:\w+[- ])?(?:low|high|negative|positive)\s+(?:T\s+)?cells",
    ],
    "Diagnostic workup": [
        r"diagnostic workup",
        r"staging",
        r"imaging",
        r"evaluation",
        r"initial assessment",
        r"diagnostic evaluation",
    ],
    "Treatment indication": [
        r"indicated",
        r"candidate",
        r"eligible",
        r"appropriate for",
        r"indication",
        r"who should receive",
        r"which patients.*candidates",
        r"(?:FDA|fda)\s+(?:approval|approved)",
        r"approved\s+(?:for|indication)",
        r"in\s+which\s+(?:of\s+the\s+following\s+)?indication",
        r"which\s+(?:of\s+the\s+following\s+)?indication",
        r"treatment\s+of.*in\s+which",
        r"for\s+(?:the\s+)?treatment\s+of.*(?:which|what)",
    ],
    "Study Design": [
        r"trial design",
        r"study design",
        r"patient population.*evaluated",
        r"being evaluated",
        r"enrolled in",
        r"which patients.*enrolled",
        r"what.*population.*trial",
    ],
    "Patient-centered care": [
        r"shared decision",
        r"quality of life",
        r"patient counseling",
        r"patient preference",
        r"patient experience",
    ],
}

# Topic normalization map (variants -> canonical)
TOPIC_NORMALIZATION = {
    # Case variations
    "Clinical Efficacy": "Clinical efficacy",
    "clinical efficacy": "Clinical efficacy",
    "Treatment Selection": "Treatment selection",
    "treatment selection": "Treatment selection",
    "Safety Profile": "Safety profile",
    "safety profile": "Safety profile",
    "AE Management": "AE management",
    "ae management": "AE management",
    "Biomarker Testing": "Biomarker testing",
    "biomarker testing": "Biomarker testing",
    "Molecular Testing": "Biomarker testing",
    "molecular testing": "Biomarker testing",
    "Mechanism of Action": "Mechanism of action",
    "mechanism of action": "Mechanism of action",
    "Study design": "Study Design",
    "study design": "Study Design",
    "Patient-Centered Care": "Patient-centered care",
    "patient-centered care": "Patient-centered care",

    # Variants
    "MoA": "Mechanism of action",
    "moa": "Mechanism of action",
    "MOA": "Mechanism of action",
    "ADC Target": "Mechanism of action",
    "ADC target": "Mechanism of action",
    "adc target": "Mechanism of action",
    "Mechanism of action/drug target or resistance": "Mechanism of action",
}

# Answer content patterns (to reinforce topic classification)
ANSWER_PATTERNS = {
    "Treatment selection": [
        r"\b(osimertinib|pembrolizumab|trastuzumab|capmatinib|amivantamab|mobocertinib|tucatinib|alectinib|tepotinib|trametinib|binimetinib|mirvetuximab|datopotamab|sacituzumab|trastuzumab deruxtecan|t-dxd|t-dm1|tafasitamab|lenalidomide|carfilzomib|daratumumab|rituximab|ibrutinib|venetoclax|azacitidine|decitabine|nivolumab|atezolizumab|durvalumab|avelumab|cemiplimab|dostarlimab)\b",
        r"\b(plus|combination|regimen|therapy|treatment)\b",
    ],
    "Clinical efficacy": [
        r"\b(orr|pfs|os|response rate|survival|benefit|improved|efficacy)\b",
        r"\d+%",  # Percentage (often response rates)
    ],
    "Safety profile": [
        r"\b(mucositis|stomatitis|neutropenia|thrombocytopenia|anemia|diarrhea|nausea|vomiting|fatigue)\b",
        r"\b(rash|pruritus|hypertension|pneumonitis|interstitial lung disease|ild|peripheral neuropathy)\b",
        r"\b(ocular toxicity|keratitis|dry eye|infusion.*reaction|irr|hypersensitivity|allergic)\b",
        r"\b(cardiac|qt.*prolongation|ejection fraction|lvef|hepatotoxicity|elevated.*lft|transaminase)\b",
        r"\b(renal|creatinine|proteinuria|second primary|malignancy|tumor lysis|cytokine release)\b",
        r"\b(adverse event|ae|toxicity|side effect|safety)\b",
    ],
    "AE management": [
        r"(discontinue|hold|dose reduction|reduce dose|stop|manage|treat|supportive)",
        r"(steroid|diphenhydramine|antihistamine|gcsf|growth factor)",
    ],
    "Biomarker testing": [
        r"\b(her2|egfr|alk|ros1|kras|braf|pdl1|pd-l1|trop2|ret|nrg1|esr1|pten|akt|idh1|flt3|npm1|kmt2a|met|her3|trk|dll3|b7-h3|menin)\b",
        r"\b(testing|test|biomarker|molecular|genetic|biopsy|ngs|genomic|sequencing|pcr|fish|ihc|immunohistochemistry)\b",
        r"\b(sample source|liquid.*tissue|tissue.*liquid|await.*result|wait.*result|next.*generation.*sequencing|tumor.*profiling|molecular.*profiling|genetic.*profiling)\b",
    ],
    "Mechanism of action": [
        r"\b(target|targets|pathway|mechanism|inhibits|blocks|binds|receptor|kinase)\b",
        r"\b(trop2|b7-h3|dll3|menin|ros1|trk|alk|her2|her3|egfr|met|ret|nrg1|braf|kras|pik3ca|mek|erk|mtor|akt)\b",
    ],
    "Study Design": [
        r"\b(population|enrolled|evaluated|design|cohort|arm)\b",
    ],
}

# Case vignette indicators (for AE management detection)
CASE_VIGNETTE_INDICATORS = [
    r"patient.*develops",
    r"patient.*presents",
    r"your patient",
    r"a patient",
    r"the patient",
    r"patient.*treated",
    r"patient.*receiving",
    r"^a \d+.*year.*old",
    r"^a \d+.*yo",
    r"^a \d+.*male",
    r"^a \d+.*female",
    r"^a \d+.*woman",
    r"^a \d+.*man",
    r"was diagnosed",
    r"is diagnosed",
    r"presents to",
    r"arrives to",
]
